name: Trigger image scanning on pull request and changes to pr
on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  deploy:
    name: Trigger image scanning
    runs-on: ubuntu-latest
    continue-on-error: true
    env:
      PEAK_USER_ID: 8877
      BRANCH: ${{ github.head_ref }}
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get changed directories
        id: changed-directories
        uses: tj-actions/changed-files@v23
        with:
          files_ignore: |
            *.md
            .github/workflows
          dir_names: true

      - name: List all changed directories/images
        run: |
          for directory in ${{ steps.changed-directories.outputs.all_changed_files }}; do
            echo "$directory was changed"
          done
    
      - name: Run docker build on changed images
        run: |
          for directory in ${{ steps.changed-directories.outputs.all_changed_files }}; do
            tag=$(echo $directory | tr / -)
            echo "Building $directory"
            docker build $directory --build-arg PEAK_USER_ID=$PEAK_USER_ID -t $tag
          done
      
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v1

      # - name: Build
      #   uses: docker/build-push-action@v3
      #   with:
      #     context: .
      #     push: true
      #     tags: user/app:latest

      - name: Run snyk scan on changed images
        run: |
          npx snyk auth $SNYK_TOKEN
          for directory in ${{ steps.changed-directories.outputs.all_changed_files }}; do
            tag=$(echo $directory | tr / -)
            npx snyk container test $tag --json >> output.json
            cat output.json | snyk-to-html -o /tmp/$BRANCH/$tag.html
          done
      
      - name: Push scan results to github pages
        run: |
          mkdir /tmp/gh-pages && cd /tmp/gh-pages
          git init && git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git checkout -b gh-pages
          git pull origin gh-pages
          git config --local user.email "scanner@peak.ai"
          git config --local user.name "github-actions[bot]"
          rm -rf $BRANCH
          cp -R /tmp/$BRANCH $BRANCH
          git add $BRANCH
          git commit -m "Add file for ${BRANCH}"
          git push origin gh-pages 
