name: Trigger image scanning on pull request and changes to pr
on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  deploy:
    name: Trigger image scanning
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v23
        with:
          files_ignore: |
            *.md
            .github/workflows
          dir_names: true

      - name: List all changed folders
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done
      
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v1

      # - name: Build
      #   uses: docker/build-push-action@v3
      #   with:
      #     context: .
      #     push: true
      #     tags: user/app:latest

      - name: Run snyk scan on changed folders
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            tag=$(echo $file | tr / -)
            docker build $file --build-arg PEAK_USER_ID=8877 -t $tag
            npx snyk container test $file --json
          done
